from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
driver = webdriver.Chrome()
driver.get("https://automationexercise.com/")
elem = driver.find_element(By.XPATH,"/html/body/header/div/div/div/div[2]/div/ul/li[4]/a")
elem.click()
elem = driver.find_element(By.XPATH,"/html/body/section/div/div/div[3]/div/form/input[2]")
elem.send_keys("yasser")
elem = driver.find_element(By.XPATH,"/html/body/section/div/div/div[3]/div/form/input[3]")
elem.send_keys("yasser99@gmail.com")
elem = driver.find_element(By.XPATH,"/html/body/section/div/div/div[3]/div/form/button")
elem.click()
elem = driver.find_element(By.XPATH,"/html/body/section/div/div/div/div[1]/form/div[1]/div[1]/label/div")
elem.click()
elem = driver.find_element(By.XPATH,"/html/body/section/div/div/div/div[1]/form/div[2]/input")
elem.send_keys("yasser")
driver.execute_script("arguments[0].scrollIntoView(true);",elem)
elem.click()
wait = WebDriverWait(driver, 10)
elem = driver.find_element(By.XPATH,"/html/body/section/div/div/div/div[1]/form/div[4]/input")
elem.send_keys("yasser")
elem = driver.find_element(By.XPATH,"/html/body/section/div/div/div/div[1]/form/p[1]/input")
elem.send_keys("yasser")
elem = driver.find_element(By.XPATH,"/html/body/section/div/div/div/div[1]/form/p[2]/input")
elem.send_keys("ramzy")
elem = driver.find_element(By.XPATH,"/html/body/section/div/div/div/div[1]/form/p[4]/input")
elem.send_keys("alexandria,smouha")
elem = driver.find_element(By.XPATH,"/html/body/section/div/div/div/div[1]/form/p[7]/input")
elem.send_keys("alexandria")
elem = driver.find_element(By.XPATH,"/html/body/section/div/div/div/div[1]/form/p[8]/input")
elem.send_keys("alex")
elem = driver.find_element(By.XPATH,"/html/body/section/div/div/div/div[1]/form/p[9]/input")
elem.send_keys("00000")
elem = driver.find_element(By.XPATH,"/html/body/section/div/div/div/div[1]/form/p[10]/input")
elem.send_keys("0123123123")
elem = driver.find_element(By.XPATH,"/html/body/section/div/div/div/div[1]/form/button")
elem.click()
elem = driver.find_element(By.XPATH,"/html/body/section/div/div/div/div/a")
elem.click()
elem = driver.find_element(By.XPATH,"/html/body/header/div/div/div/div[2]/div/ul/li[5]/a")
elem.click()